4.2.1用ページ追加
EC-CUBE/doc4.ec-cube.net pull request #300
Opened 2023-02-13 01:06 UTC by KenTanaka

2023-02-13 06:19 UTC, chihiro-adachi requested changes

2023-02-13 06:19 UTC, chihiro-adachi commented on _pages/quickstart/update421.md
> +<a href="https://github.com/EC-CUBE/ec-cube/pulls?q=is%3Apr+label%3Aaffected%3Atemplate+is%3Aclosed+milestone%3A4.1.1" target = "_blank">フロントテンプレートファイルの差分</a>
以下URLをご利用ください
https://github.com/EC-CUBE/ec-cube/pulls?q=is%3Apr+label%3Aaffected%3Atemplate+is%3Aclosed+milestone%3A4.2.1+

2023-02-13 06:19 UTC, chihiro-adachi commented on _data/navigation.yml
> +        output: web, pdf
```
title: 4.2本体バージョンアップ
url: /update42x
```
でお願いします

記載位置は`4.1本体バージョンアップ`の上でお願いします

2023-02-13 06:19 UTC, chihiro-adachi commented on _data/navigation.yml
>        - title: 4.1から4.2へのマイグレーション
```
title: 4.2本体バージョンアップ
url: /update42x
```
でお願いします。


記載位置は、`4.1本体バージョンアップ`の上でお願いします

2023-02-13 06:19 UTC, chihiro-adachi commented on _pages/quickstart/update421.md
> +permalink: update421
ファイル名も、`update42x.md`
でお願いします

2023-02-13 06:20 UTC, chihiro-adachi commented
@KenTanaka 
コメントしました。アップデート手順自体は問題ないです。
文言の修正お願いします。

2023-02-14 04:49 UTC, KenTanaka commented on _pages/quickstart/update421.md
> +permalink: update421
修正しました。

2023-02-14 04:50 UTC, KenTanaka commented on _pages/quickstart/update421.md
> +summary : 4.2.1 の本体バージョンアップ手順について記載します。
修正しました。

2023-02-14 04:50 UTC, KenTanaka commented on _pages/quickstart/update421.md
> +{: .notice--danger}
削除しました。

2023-02-14 04:50 UTC, KenTanaka commented on _pages/quickstart/update421.md
> +<a href="https://github.com/EC-CUBE/ec-cube/pulls?q=is%3Apr+label%3Aaffected%3Atemplate+is%3Aclosed+milestone%3A4.1.1" target = "_blank">フロントテンプレートファイルの差分</a>
上のURLに差し替えました。

2023-02-14 04:51 UTC, KenTanaka commented on _data/navigation.yml
> +        output: web, pdf
ページ位置、URL指定変更しました。

2023-02-14 04:51 UTC, KenTanaka commented on _data/navigation.yml
>        - title: 4.1から4.2へのマイグレーション
ページ位置変更しました。

2023-02-14 04:52 UTC, KenTanaka commented
当該手順書の通り
　4.2.0環境構築 > 4.2.1バージョンアップ
にて、正しくアップデート、動作する事を確認しました。

2023-02-15 00:59 UTC, merged