4.2.3変更分を記載
EC-CUBE/doc4.ec-cube.net pull request #318
Opened 2023-09-21 10:51 UTC by KenTanaka

#6038

2023-09-22 07:52 UTC, dotani1111 requested changes

2023-09-22 07:52 UTC, dotani1111 commented on _pages/customize/customize_throttling.md
> +| 会員登録(完了) | entry | 5回/30分 | - |  |
@shinya 
会員登録完了はentry_completeになります。

2023-09-22 08:53 UTC, shinya commented on _pages/customize/customize_throttling.md
> +| 会員登録(完了) | entry | 5回/30分 | - |  |
@dotani1111 
ありがとうございます。直しておきました！

2023-09-28 08:06 UTC, chihiro-adachi approved these changes

2023-09-28 08:13 UTC, kiy0taka approved these changes

2023-09-29 04:48 UTC, merged